### ISSUE TITLE
After a failing test, variables are not backtracked to their values before the test

### ISSUE THREAD

**Issue by pschachte** [pschachte/wybe#411] opened 2023-10-13 10:01 UTC
Here's an example:
```
def {test,noinline} nope { fail }

def yup use !io {
    ?x = 42
    if { ?x = 24 ; nope :: !println("nope succeeds: x = $x")
       | else :: !println("nope fails; x = $x")
       }
    !println("after conditional; x = $x")
}

!yup
```
This prints
```
nope fails; x = 24
after conditional; x = 24
```
when it should print
```
nope fails; x = 42
after conditional; x = 42
```

**Comment by pschachte** [comment] 2023-10-13 22:28
Addendum:  even a semidet call can modify its output arguments.  Here's a more complete test case to illustrate:

```
def {test,noinline} nope { fail }
def {test,noinline} nope2(?value:int) { ?value = 2; fail }

?x = 42
!println("before conditional: x = $x")
if { ?x = 24 ; nope :: !println("nope succeeds: x = $x")
    | else :: !println("nope fails; x = $x")
    }
!println("after conditional; x = $x")

?x = 42
!println("before second conditional: x = $x")
if { nope2(?x) :: !println("nope2 succeeds: x = $x")
    | else :: !println("nope2 fails; x = $x")
    }
!println("after second conditional; x = $x")

```
Should print:
```
before conditional: x = 42
nope fails; x = 42
after conditional; x = 42
before second conditional: x = 42
nope2 fails; x = 42
after second conditional; x = 42
```
but actually prints:
```
before conditional: x = 42
nope fails; x = 24
after conditional; x = 24
before second conditional: x = 42
nope2 fails; x = 2
after second conditional; x = 2
```

**Comment by jimbxb** [comment] 2023-10-14 05:50
This issue is caused by unbranching and the clausal form transformation. When unbranched, a test like

```
?x = 10
if { test(?x) :: pass }
!print(x)
```

gets transformed into

```
?x = 10
test(?x, ?b)
if { b :: pass }
!print(x)
```

which shadows the old binding of `x`. From here, the clausal form produced is 

```
?x#0 = 10
test(?x#1, ?b#0)
case b
0 ::
    !print(x#1)
1 ::
    pass
    !print(x#1)
```
whereas it should be more like
```
?x#0 = 10
test(?x#1, ?b#0)
case b
0 ::
    !print(x#0)
1 ::
    pass
    !print(x#1)
```

**Comment by pschachte** [comment] 2023-10-19 04:16
Yes, that's exactly the problem.  Because of the way unbranching works (ie, it happens before LPVM generation, so before we have single assignment form), I think it will be easier to generate something more like this:
```
?x = 10
?temp = x
test(?x, ?b)
if { b :: pass | ?x = temp }
!print(x)
```
Where this gets trickier is with code like this:
```
?x = 10 ; ?y = 42
if { test1(?x) ; test2(?y) :: pass }
!println(x)
!println(y)
```
which would need to be translated into
```
?x = 10 ; ?y = 42
?temp1 = x
test1(?x, ?b)
if { b :: 
    ?temp2 = y
    test2(?y, ?b2)
    if { b2 :: pass | ?y = temp2 ; ?x = temp1 }
  | ?x = temp1
 }
!println(x)
!println(y)
```
That's what I'm working on generating.

So the big question:  assuming I do this for variables that happen to be resources, will the same fix also fix the problem with resources being clobbered by failing tests?

**Comment by jimbxb** [comment] 2023-10-19 04:26
I think I already generate code like this for resources that are currently. The clobbering issue occurs for resources that aren't explicitly in scope (but are in some parent scope), and this wouldn't fix that.

I'm concerned, though, if we do generate a bunch of temporary variables, that these variables could affect unbranching, causing more procs to get factored. More factored procs means less intra-proc optimisations are available.

**Comment by pschachte** [comment] 2023-10-19 04:41
Yes, the factoring is a concern.   We already have a longstanding performance bug report about factoring and the way it passes variables around unnecessarily.  In this case, the code we're adding is just a bunch of assignments; we can tweak the heuristic that decides what to factor out and what to keep inline to keep around variable assignments.  In fact, after transformation to single assignment, it will just pass the saved variable in place of the smashed variable to the factored proc.

Longer term, I'd like to resurrect the idea of some LPVM procs being defined wholly within others, meaning they are only called from the containing proc, which should make forward analysis much easier.  Then, when generating LLVM, we could turn them into labels within the containing proc, which should allow for better LLVM code generation.

**Comment by jimbxb** [comment] 2023-10-19 04:48
Perhaps that could work. If the heuristic just sets the "cost" of a move to 0, then there is no "penalty" for introducing a move. Potentially also, we could have a foreign instruction flag, `no_factor_penalty`, to handle this, instead of treating moves specially?

**Comment by pschachte** [comment] 2023-10-19 04:55
Actually, it's probably right to set the cost of a move in that context to 0, since the move is just going to turn into an argument to the factored proc, while if the move is part of the factored proc, it'll have to be done as an actual move.  So the cost of a move there is actually negative.

**Comment by jimbxb** [comment] 2023-10-19 04:55
Also, why can't we just store all assigned variables in a test, and reassign in the else branch?

```
?tempX = x; ?tempY = y
test1(?x, ?b1
if { b1 ::
    test2(?y, ?b2)
    if { b2 ::
        pass
      | else :: ?x = tempX; ?y = tempY
    }
  
  | else :: ?x = tempX; ?y = tempY
}

```

**Comment by pschachte** [comment] 2023-10-19 05:03
I'll have to think about that more; if you're right, that would be a nice simplification.  It would clean it up in cases where the continuation is big enough to factor out, but in other cases, it might not.

I think disjunctions are turned into conditionals before unbranching (or maybe as part of unbranching?), so I think we get them for free.  If not, yes, disjunctions have the same issue.

**Closed** 2023-11-09 12:00 UTC
Labels: bug
