### ISSUE TITLE
Unable to compile use_resource.wybe (one of the test cases)

### ISSUE THREAD

**Issue by 09milk** [pschachte/wybe#85] opened 2020-08-13 05:23 UTC
trying to compile test cases inside [`/test-cases/final-dump/`](https://github.com/pschachte/wybe/blob/master/test-cases/final-dump/), [`use_resource.wybe`](https://github.com/pschachte/wybe/blob/master/test-cases/final-dump/use_resource.wybe) gives error related to the use of resources

`$wybemk use_resource` 
gives the following error:
`Unknown resource use_resource.count`
while
`$wybemk use_resource.o`
gives no error

**Comment by pschachte** [comment] 2020-09-17 07:19
This is a duplicate of #7

**Closed by pschachte** 2020-09-17 07:19 UTC
Labels: duplicate, enhancement
